### ISSUE TITLE
anchor test: program not found

### ISSUE THREAD

**Issue by Kidkender** [coral-xyz/anchor#3153] opened 2024-08-05 11:00 UTC
### Hi,
after i just started the init project and i built the default program using anchor build. After that, I continued to use the anchor test but the result was program not found.

Failed to run test: yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts: program not found
Error: yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts

**Caused by:
    program not found**

i tried again with command 
yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts
then the result was successful, so what is the cause here and is there any mistake?

**Comment by acheroncrypto** [comment] 2024-08-05 11:57
What is your OS?

**Comment by Kidkender** [comment] 2024-08-05 16:30
> What is your OS?

I using windows

**Comment by acheroncrypto** [comment] 2024-08-06 20:53
I think this is a Windows specific issue, which was also mentioned in https://github.com/coral-xyz/anchor/issues/2093.

The test validator didn't work either for Windows last I checked, so I'd recommend using WSL instead when developing on Windows.

Closing because this is a duplicate of https://github.com/coral-xyz/anchor/issues/2093.

**Closed by acheroncrypto** 2024-08-06 20:53 UTC
Labels: duplicate, cli
