### ISSUE TITLE
OS Error 1 on MacM1

### ISSUE THREAD

**Issue by Killpit** [coral-xyz/anchor#2499] opened 2023-05-20 22:22 UTC
For more details, please visit https://support.apple.com/kb/HT208050.
atatekeli:cNFT-implementation atatekeli$ cd cnft-anchor
atatekeli:cnft-anchor atatekeli$ yarn
Usage: yarn [OPTIONS] SUBCOMMAND [SUBCOMMAND OPTIONS]
 or    yarn [OPTIONS] CLASSNAME [CLASSNAME OPTIONS]
  where CLASSNAME is a user-provided Java class

  OPTIONS is none or any of:

--buildpaths                       attempt to add class files from build tree
--config dir                       Hadoop config directory
--daemon (start|status|stop)       operate on a daemon
--debug                            turn on shell script debug mode
--help                             usage information
--hostnames list[,of,host,names]   hosts to use in worker mode
--hosts filename                   list of hosts to use in worker mode
--loglevel level                   set the log4j level for this command
--workers                          turn on worker mode

  SUBCOMMAND is one of:

    Admin Commands:

daemonlog            get/set the log level for each daemon
node                 prints node report(s)
rmadmin              admin tools
scmadmin             SharedCacheManager admin tools

    Client Commands:

applicationattempt   prints applicationattempt(s) report
app|application      prints application(s) report/kill application/manage long running application
classpath            prints the class path needed to get the hadoop jar and the required libraries
cluster              prints cluster information
container            prints container(s) report
envvars              display computed Hadoop environment variables
fs2cs                converts Fair Scheduler configuration to Capacity Scheduler (EXPERIMENTAL)
jar <jar>            run a jar file
logs                 dump container logs
nodeattributes       node attributes cli client
queue                prints queue information
schedulerconf        Updates scheduler configuration
timelinereader       run the timeline reader server
top                  view cluster information
version              print the version

    Daemon Commands:

nodemanager          run a nodemanager on each worker
proxyserver          run the web app proxy server
registrydns          run the registry DNS server
resourcemanager      run the ResourceManager
router               run the Router daemon
sharedcachemanager   run the SharedCacheManager daemon
timelineserver       run the timeline server

SUBCOMMAND may print help when invoked w/o parameters or with -h.
atatekeli:cnft-anchor atatekeli$ anchor build
Error: Error reading the directory with path: /Users/atatekeli/Documents/GitHub

Caused by:
    Operation not permitted (os error 1)

**Comment by acheroncrypto** [comment] 2023-06-12 12:56
Seems like duplicate of https://github.com/coral-xyz/anchor/issues/2525, closing.

**Closed by acheroncrypto** 2023-06-12 12:56 UTC
Labels: duplicate
