### ISSUE TITLE
v0.30.1 Does Not Include the Fix from Upgrade time to 0.3.36 (#3143)

### ISSUE THREAD

**Issue by liompei** [coral-xyz/anchor#3198] opened 2024-08-26 05:05 UTC
The v0.30.1 version of Anchor was released on June 20th, so it does not include the fix from "Upgrade time to 0.3.36" (#3143).

After I run cargo install --git https://github.com/coral-xyz/anchor avm --locked --force to install avm, and then execute avm install latest, it installs the v0.30.1 version. However, this version still throws the following error:

error[E0282]: type annotations needed for `Box<_>`
  --> /Users/dawn/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.29/src/format_description/parse/mod.rs:83:9
This issue is difficult for new users to resolve, so I have two questions:

How can I resolve this issue with the current setup? (Please provide detailed steps)
When is the new version expected to be released?

**Comment by liompei** [comment] 2024-08-26 05:07
@acheroncrypto

**Comment by acheroncrypto** [comment] 2024-08-26 11:24
Please see the "Note" section of https://github.com/coral-xyz/anchor/pull/3143.

Duplicate of https://github.com/coral-xyz/anchor/issues/3126, https://github.com/coral-xyz/anchor/issues/3158, https://github.com/coral-xyz/anchor/issues/3164, https://github.com/coral-xyz/anchor/issues/3169, https://github.com/coral-xyz/anchor/issues/3173.

**Closed by acheroncrypto** 2024-08-26 11:24 UTC
Labels: duplicate, avm, installation error
