### ISSUE TITLE
Anchor fails to deserialize `#[account]` annotated types as instruction arguments even though they're defined in the IDL.

### ISSUE THREAD

**Issue by 0xcrust** [coral-xyz/anchor#2545] opened 2023-06-26 00:00 UTC
Something like:
```rust
#[account] 
pub struct State { x: u64, ... }
```
cannot be used as the type of an input to some instruction:
```rust
pub fn initialize(ctx: Context<Initialize>, input: State) -> Result<()> {
    ctx.accounts.state.set_inner(state); ...
}
```
Deserialization fails on the client with `IdlError: Type not found: {"name":"input","type":{"defined":"State"}}` even though the `State` type is defined in the IDL.

Attempting this:
```rust
#[derive(AnchorSerialize, AnchorDeserialize)
pub struct StateEntry(State);
```
as a bypass doesn't work. It looks like tuple structs aren't supported.

Neither does:
```rust
#[derive(AnchorSerialize, AnchorDeserialize)
#[account]
pub struct State { x: u64 };
```
due to multiple derived implementations.

This means users need to write a mirror type for the `State` type, which seems unnecessary. For example:
```rust
impl From<StateEntry> for State {
    fn from(se: StateEntry) -> Self {
        State {
            update_authority: se.update_authority,
            marinade_state: se.marinade_state,
            sunrise_state: se.sunrise_state,
            vault_authority_bump: se.vault_authority_bump,
            treasury: se.treasury,
        }
    }
}
```
is code I had to write to get around this

**Comment by SushantChandla** [comment] 2023-07-06 06:12
Indeeed I have the same issue. This is because of the idl. In the args of my instruction: 
```
  "args": [
        {
          "name": "state",
          "type": {
            "defined": "State"
          }
        }
      ]
```
I think it is caused by the   `"defined": "State"` State being in capital. I changed it to `state` manual and it worked. But thi is not a solution. Adding a extra type because of this.

**Comment by acheroncrypto** [comment] 2024-03-10 18:01
Fixed by https://github.com/coral-xyz/anchor/pull/2824.

**Closed by acheroncrypto** 2024-03-10 18:01 UTC
Labels: bug, lang, idl
