### ISSUE TITLE
Method does not support views

### ISSUE THREAD

**Issue by ahpb21** [coral-xyz/anchor#2648] opened 2023-10-05 07:39 UTC
const returnData = await program.methods
  .calculate(someVariable)
  .accounts({
    acc: somePubkey,
    anotherAcc: someOtherPubkey,
  })
  .view()  // Method does not support views

**Comment by acheroncrypto** [comment] 2023-10-05 08:23
`view` method is only supported if `calculate` instruction returns a value.

**Comment by acheroncrypto** [comment] 2023-10-07 11:45
Closing because there isn't enough information to reproduce and good chance this error is by design.

**Closed by acheroncrypto** 2023-10-07 11:45 UTC
Labels: ts
