### ISSUE TITLE
Error migrating from Anchor 0.29.0 to 0.30.1 - Unable to pass &AccountInfo as an argument to a validation function in an Instruction

### ISSUE THREAD

**Issue by gwalen** [coral-xyz/anchor#3448] opened 2024-12-23 08:45 UTC
I’m migrating my code from Anchor 0.29.0, where everything was working correctly.

I need to pass an account as `&UncheckedAccount` or `&AccountInfo` to a static method which extracts a value from raw data that will be used as part of the PDA seed.

Here is the code that is now broken:

```rust
#[account(
    mut,
    seeds = [ 
         UserMessageNonce::SEED_PREFIX,
         sender.key().as_ref()
    ],
    bump
)]
pub user_message_nonce: AccountInfo<'info>,

#[account(
    mut,
    seeds = [
         SEED_PREFIX_SENT,         
         &UserMessageNonce::value(&user_message_nonce).to_le_bytes(), // BREAKS HERE
         sender.key().as_ref()
    ],
    bump,
)]
pub other_account: UncheckedAccount<'info>,    
```

When I compile this, I encounter the following error:

```
error[E0425]: cannot find value `user_message_nonce` in this scope
   --> programs/my_program/src/instructions/generic_send_message.rs:134:39
    |
134 |             &UserMessageNonce::value(&user_message_nonce).to_le_bytes(),
    |                                       ^^^^^^^^^^^^^^^^^^ not found in this scope
```

At the moment, the only workaround I’ve found is to avoid providing the seed in the Instruction and instead validate the account address in the code. However, this solution is neither optimal nor clear.

**Comment by docongminh** [comment] 2024-12-27 03:10
@gwalen I think you shouldnt check constraint in account rather than check inside logic of program.

**Comment by acheroncrypto** [comment] 2024-12-27 05:35
Thanks for creating this issue, but this is a duplicate of https://github.com/coral-xyz/anchor/issues/2903, so I'm closing this to not divert attention from the existing issue. However, feel free to reopen if you think this is a different issue.

I think the parser needs to be smarter about external functions and omit resolution data when necessary. At the very least, we should show a better error message that explains why the error happens. In the meantime, please consider the workaround mentioned in https://github.com/coral-xyz/anchor/issues/2903#issuecomment-2053637446.

**Closed by acheroncrypto** 2024-12-27 05:35 UTC
Labels: lang, idl
