### ISSUE TITLE
createAssociatedTokenAccount function seems broken

### ISSUE THREAD

**Issue by bubu59** [coral-xyz/anchor#2154] opened 2022-08-27 16:46 UTC
When initializing token accounts in the test folder ( localnet) , an error pops up saying `custom program error: 0x0` 
![image](https://user-images.githubusercontent.com/74093051/187039641-ec62bc9e-4a5e-453b-8041-8cf6056aeccb.png)

I have narrowed it down to this particular token account.. When I remove it, creating the other token accounts work... 
![image](https://user-images.githubusercontent.com/74093051/187039819-3b62d1a1-3c0c-4e07-89da-2c301227b89b.png)

I have checked the discord for some answers regarding the error message but I'm not `init` the fundraiser_token_account as seen in the image above. I'm not really not sure why this is so since it has never happened before this.. Any advice would be greatly appreciated!!

**Comment by chinepun** [comment] 2022-08-28 00:38
It seems `fundraiser` is expected to create the token account but It does not have enough SOL to pay for rent, Consider doing an airdrop to `fundraiser`

**Comment by bubu59** [comment] 2022-08-28 08:42
Alr did.. Still having the same error! 
![image](https://user-images.githubusercontent.com/74093051/187065498-a77bc2e2-b1c8-4ac8-8c63-1883fbd24627.png)

**Comment by djordjevucinic** [comment] 2022-08-28 16:29
I've had a similar issue, 0x0 too, what I did is renamed ./.config/solana/id.json to id_whatever.json and generated a new keypair - airdropped a few SOL and voila, the problem was that even though you generate a new keypair each time, the token account was already created somehow, and it won't create it again.

**Comment by bubu59** [comment] 2022-08-29 14:50
Oh. Um, I'm currently testing on the local net and have airdropped enough sol to the fundraiser account . Like so, 
![image](https://user-images.githubusercontent.com/74093051/187229662-ffc64565-5038-4247-97ab-8794f008cf28.png)

**Comment by chinepun** [comment] 2022-08-29 17:27
I have noticed that airdropping SOL to an Account in the local net may not always be successful, I would suggest checking the balance of the account after the airdrop. If there is no SOL after the airdrop, I suggest sending SOL from your anchor provider wallet as it has a starting balance of 500 SOL when testing on the local net. Send SOL from the wallet and check the balance of the fundraiser account, this should work, and hence you will have enough SOL to cover for creating a token account :)

**Comment by djordjevucinic** [comment] 2022-08-29 20:47
Have you tried deleting the id.json and creating a new one or are you not using it at all?

**Comment by Henry-E** [comment] 2022-08-29 20:51
Recommend asking on https://solana.stackexchange.com/ and closing this issue as this appears to not be an issue with anchor itself but the solana runtime or how you're using anchor (e.g. not enough solana in the payer account).

**Comment by acheroncrypto** [comment] 2023-11-01 09:04
The problem is you're trying to create a token account that already exists but as previous comment suggested, this is not a problem with Anchor and `createAssociatedTokenAccount` function doesn't even come from Anchor.

**Closed by acheroncrypto** 2023-11-01 09:04 UTC
Labels: invalid
