### ISSUE TITLE
Cannot init anchor project giving yarn error

### ISSUE THREAD

**Issue by Zaid-maker** [coral-xyz/anchor#1821] opened 2022-04-21 13:29 UTC
I successfully installed anchor-cli after 4th attempt and it takes 59 minutes to install so after that i hope over to my terminal and do `anchor init programs` but it gives me yarn error even the yarn is installled globally. I dont know what's wrong with it please help me.

ERROR:
![image](https://user-images.githubusercontent.com/53424436/164468724-b4ee734c-f4b6-42be-b2aa-e11d58561088.png)

Yarn version:
![image](https://user-images.githubusercontent.com/53424436/164468417-d91bf7df-a2b0-4325-9ea4-fce1ee9383e8.png)

nodejs version:
![image](https://user-images.githubusercontent.com/53424436/164468511-0731e526-fc62-487b-9b49-1372d5ba7f0f.png)

**Comment by Zaid-maker** [comment] 2022-04-24 13:10
Please help someone @siong1987 @SvenDowideit @jeduan @guanqun

**Comment by fanatid** [comment] 2022-04-25 17:56
https://github.com/project-serum/anchor/pull/1835 should help with this issue :thinking:

**Comment by Zaid-maker** [comment] 2022-04-25 17:57
Ok let me see

**Comment by Zaid-maker** [comment] 2022-04-25 17:58
> https://github.com/project-serum/anchor/pull/1835 should help with this issue :thinking: 

Yes bro that would be so cool

**Comment by sarkarshubhanshuk** [comment] 2022-09-15 19:51
Hello, has this been resolved yet?

**Comment by acheroncrypto** [comment] 2023-07-28 20:24
Closing because not enough information to reproduce it and it also hasn't been reported in a long time.

**Closed by acheroncrypto** 2023-07-28 20:24 UTC
Labels: installation error

**Comment by Zaid-maker** [comment] 2023-07-28 20:32
xD
