### ISSUE TITLE
IDL: Generation fails if struct is not from the same program.

### ISSUE THREAD

**Issue by SushantChandla** [coral-xyz/anchor#2531] opened 2023-06-14 06:14 UTC
If we have 2 programs one of them has a account T:

Program1:
```
pub struct T{
pub seeds: String
}
```

And in the second program for the context if I try to do something like:
Program2:

```rust
use program1::struct::T;

pub struct Accounts{
#[account(
        seeds = [account_t.seeds.as_bytes()],
        bump ,
        seeds::program = program1::ID,
    )]
  pub account_t: Account<T>
}
```

Fails as an option is unwrapped:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', lang/syn/src/idl/pda.rs:225:37
```

**Comment by tanmaymunjal** [comment] 2023-07-08 10:10
Hey @SushantChandla, thanks for raising the issue

I am not able to reproduce this error on my local. Can you please check if you have enabled the seeds flag under features in Anchor.toml. Also when adding the program from which the struct is imported in your Cargo.toml, have you added the no-entrypoint feature to the program?

If the problem still persists, please share the Anchor.toml and Cargo.toml files of the program here. I am using anchor v0.28.0 on my local for context if you are on some other version.

**Comment by tanmaymunjal** [comment] 2023-07-08 10:30
Hey @SushantChandla, thanks for raising the issue

I was not able to reproduce this issue on my local. Can you please post the Anchor.toml and Cargo.toml configurations here? Also would be helpful if you could upload a complete piece of code on which this issue is easily reproducable.I am using Anchor v.28.0 on my programs just for context.

**Comment by acheroncrypto** [comment] 2024-03-10 18:00
Fixed in https://github.com/coral-xyz/anchor/pull/2824.

**Closed by acheroncrypto** 2024-03-10 18:00 UTC
Labels: idl
