### ISSUE TITLE
Unaligned Field Access Error when Installing anchor-cli v0.28.0

### ISSUE THREAD

**Issue by Parikshit-007** [coral-xyz/anchor#2608] opened 2023-08-20 07:14 UTC
Description:
I am encountering an error while attempting to install anchor-cli version 0.28.0 using the cargo install command. The error seems to be related to unaligned field access in the ntapi crate. Below are the details of the issue:

Error Messages:
I am receiving the following error messages during the installation process:
error[E0793]: reference to packed field is unaligned
    --> C:\Users\ASUS\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ntapi-0.3.7\src\ntexapi.rs:2783:52
     |
2783 |         *tick_count.QuadPart_mut() = read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad);
     |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: packed structs are only aligned by one byte, and many modern architectures penalize unaligned field accesses
     = note: creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

error[E0793]: reference to packed field is unaligned
    --> C:\Users\ASUS\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ntapi-0.3.7\src\ntexapi.rs:2807:25
     |
2807 |         ((read_volatile(&(*USER_SHARED_DATA).u.TickCountQuad)
     |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: packed structs are only aligned by one byte, and many modern architectures penalize unaligned field accesses
     = note: creating a misaligned reference is undefined behavior (even if that reference is never dereferenced)
     = help: copy the field contents to a local variable, or replace the reference with a raw pointer and use `read_unaligned`/`write_unaligned` (loads and stores via `*p` must be properly aligned even when using raw pointers)

   Compiling miow v0.3.7
For more information about this error, try `rustc --explain E0793`.
error: could not compile `ntapi` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `anchor-cli v0.28.0 (https://github.com/coral-xyz/anchor?tag=v0.28.0#e1afcbf7)`, intermediate artifacts can be found at `C:\Users\ASUS\AppData\Local\Temp\cargo-installm5ALNA`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Relevant Information:

Operating System: Windows 11
Rust Version: rustc 1.73.0-nightly (076887268 2023-08-17)
Cargo Version: cargo 1.73.0-nightly (7c3904d6c 2023-08-14)
Steps Taken: I attempted to install anchor-cli using the following command:
cargo install --git https://github.com/coral-xyz/anchor --tag v0.28.0 anchor-cli --locked
Dependencies: I suspect that the issue might be related to the alignment problems in the ntapi crate.
Steps to Reproduce:
Unfortunately, I'm unable to provide exact steps to reproduce the issue, as it appears to be specific to the ntapi crate interactions within the anchor-cli installation process.

Expected Outcome:
I expect to be able to successfully install anchor-cli version 0.28.0 without encountering unaligned field access errors.

Additional Context:
I am attempting to install this version of anchor-cli in order to [mention your reason for using this specific version].

Note:
I have also considered using an older version of anchor-cli to avoid this issue, but I would like to report the problem to assist with identifying and resolving the underlying cause.

I appreciate any assistance in troubleshooting this issue and finding a solution. Thank you for your time and support.

**Comment by acheroncrypto** [comment] 2023-08-20 08:10
This is a Windows specific issue coming from `solana-client`'s dependence to `tokio 1.14`. `master` branch of Solana has been updated to use newer versions of `tokio` but it hasn't been released in `1.16`. It is also recommended to use WSL if you are developing on Windows.

Closing because this is a duplicate of https://github.com/coral-xyz/anchor/issues/2567 and the original issue will be closed once a released version of `solana-client` uses a newer version of `tokio` that doesn't have this problem.

**Closed by acheroncrypto** 2023-08-20 08:10 UTC
Labels: installation error
