### ISSUE TITLE
Rust Version Mismatch Error During anchor build Despite Correct Version Installed

### ISSUE THREAD

**Issue by Navneet-Sahota** [coral-xyz/anchor#3162] opened 2024-08-10 17:07 UTC
### Description
This is a brand new project I setup using `anchor init <project_name>`. I encountered an issue when running `anchor build` in my Solana project. The build process fails with an error message indicating that the required Rust version is not satisfied, even though my system has the correct version installed.

### Error Message
When running `anchor build`, I receive the following error:

```bash
error: package `solana-program v1.18.22` cannot be built because it requires rustc 1.75.0 or newer, while the currently active rustc version is 1.68.0-dev
Either upgrade to rustc 1.75.0 or newer, or use
cargo update -p solana-program@1.18.22 --precise ver
where `ver` is the latest version of `solana-program` supporting rustc 1.68.0-dev
```

### Expected Behavior
The build should proceed without errors, utilizing the correct version of Rust that is already installed on my system.

### Actual Behavior
The build process fails, incorrectly detecting an older version of Rust (1.68.0-dev) despite having the correct version installed.

### Environment Details
- Rust Version: rustc 1.80.1 (3f5fd8dd4 2024-08-06)
- Cargo Version: cargo 1.80.1 (376290515 2024-07-16)
- Anchor Version: anchor-cli 0.30.1
- Solana Version: solana-cli 1.17.25 (src:d0ed878d; feat:3580551090, client:SolanaLabs)
- Operating System: macOS 14.1.2 (23B92)

### Steps to Reproduce
- Setup new project using `anchor init <project_name>` & cd into it.
- Run `yarn install` & `anchor build` in the Solana project directory.
- Observe the version mismatch error.

### Attempted Solutions
- Verified that the correct Rust version is installed.
- Checked for .cargo/config and rust-toolchain files that might force an older version (none found).
- Cleaned the project with cargo clean and attempted to rebuild.

Any guidance or assistance in resolving this issue would be greatly appreciated.

**Comment by bonedaddy** [comment] 2024-08-10 22:16
Also running into this, however the error message for me is slightly different with a different rustc version indicated:

```
error: package `solana-program v1.18.22` cannot be built because it requires rustc 1.75.0 or newer, while the currently active rustc version is 1.72.0-dev
Either upgrade to rustc 1.75.0 or newer, or use
cargo update -p solana-program@1.18.22 --precise ver
where `ver` is the latest version of `solana-program` supporting rustc 1.72.0-dev
```

**Comment by acheroncrypto** [comment] 2024-08-11 06:14
Rust version is coming from the Solana installation, see https://github.com/solana-labs/solana/issues/31428.

@bonedaddy yeah that work since it overrides your Solana version, but I'd also set Anchor to `0.30.1` because it includes some important fixes.

Duplicate of https://github.com/coral-xyz/anchor/issues/3012.

**Closed by acheroncrypto** 2024-08-11 06:14 UTC
Labels: duplicate, lang, cli, compile error

**Comment by bjoerndotsol** [comment] 2024-08-13 12:36
Thanks @acheroncrypto, this worked for me 🙌 

Think the toolchain workaround is a bit hacky and might prevent you from using the latest features. Updating my Solana version, as recommended by @acheroncrypto, fixed my problem `solana-install update`, maybe you want to check this out as well?
