### ISSUE TITLE
Empty #[derive(Accounts)] struct does not compile with `cpi` feature

### ISSUE THREAD

**Issue by cavemanloverboy** [coral-xyz/anchor#2758] opened 2024-01-03 02:44 UTC
The autogenerated cpi code always adds a lifetime parameter. For some

```rust
#[derive(Accounts)]
pub struct Initialize {}
```

the macros generate
```rust
#[cfg(feature = "cpi")]
pub mod cpi {
    use super::*;
    use std::marker::PhantomData;
    pub struct Return<T> {
        phantom: std::marker::PhantomData<T>,
    }
    impl<T: AnchorDeserialize> Return<T> {
        pub fn get(&self) -> T {
            let (_key, data) = anchor_lang::solana_program::program::get_return_data()
                .unwrap();
            T::try_from_slice(&data).unwrap()
        }
    }
    pub fn initialize<'a, 'b, 'c, 'info>(
        ctx: anchor_lang::context::CpiContext<
            'a,
            'b,
            'c,
            'info,
            crate::cpi::accounts::Initialize<'info>,
        >,
        data: Vec<u8>,
    ) -> anchor_lang::Result<()> {
    // redacted
```
which does not compile due to the added lifetime parameter on `crate::cpi::accounts::Initialize<'info>`

**Comment by acheroncrypto** [comment] 2024-01-03 04:41
Duplicate of https://github.com/coral-xyz/anchor/issues/1628

There is also a draft PR to solve it: https://github.com/coral-xyz/anchor/pull/1659

**Closed by acheroncrypto** 2024-01-03 04:41 UTC
Labels: duplicate, lang
