### ISSUE TITLE
New projects on anchor-cli 0.29.0 / solana-cli 1.17.17 still having ahash errors when building

### ISSUE THREAD

**Issue by mikemaccana** [coral-xyz/anchor#2792] opened 2024-01-26 19:47 UTC
I did look for duplicates on this, but couldn't find any. Re https://github.com/rust-lang/rust/issues/86161

ahash still seems to be failing in solana-cli 1.17.17, anchor-cli 0.29.0. 

```
% anchor --version
anchor-cli 0.29.0

% solana --version
solana-cli 1.17.17 (src:27a43800; feat:1337574167, client:SolanaLabs)

% anchor init anchor-test --template=multiple

% cd anchor-test

% anchor build
<...snip...>
   Compiling solana-frozen-abi v1.17.14
   Compiling num-traits v0.2.17
   Compiling memoffset v0.9.0
   Compiling cpufeatures v0.2.12
error[E0658]: use of unstable library feature 'build_hasher_simple_hash_one'
   --> src/random_state.rs:463:5
    |
463 | /     fn hash_one<T: Hash>(&self, x: T) -> u64 {
464 | |         RandomState::hash_one(self, x)
465 | |     }
    | |_____^
    |
    = note: see issue #86161 <https://github.com/rust-lang/rust/issues/86161> for more information
    = help: add `#![feature(build_hasher_simple_hash_one)]` to the crate attributes to enable

   Compiling jobserver v0.1.27
For more information about this error, try `rustc --explain E0658`.
error: could not compile `ahash` due to previous error
```

**Comment by acheroncrypto** [comment] 2024-01-26 21:17
It's a duplicate of https://github.com/coral-xyz/anchor/issues/2755 but Anchor doesn't even have a direct dependency to `ahash`, it's coming from Solana's side https://github.com/solana-labs/solana/issues/34609.

I see in the logs you shared that it's compiling `solana-frozen-abi v1.17.14` and `ahash` wasn't fixed on that version:

https://github.com/solana-labs/solana/blob/cc7c59af9f09932168bad4b3f94e3e09d336f6be/Cargo.toml#L135

It was fixed in the next release(`1.17.15`):

https://github.com/solana-labs/solana/blob/cc0e9a0e5a6b5c3e86d52ac105dac743826afd9a/Cargo.toml#L135

There is a solution I've posted in https://github.com/coral-xyz/anchor/issues/2755#issuecomment-1872994213 but in any case, pinning is only a short-term solution and problems like this will continue to happen as long as Solana's `rustc` is outdated https://github.com/solana-labs/solana/issues/34609.

**Comment by mikemaccana** [comment] 2024-01-26 21:59
If this was fixed in 1.17.15, I don't understand why it's occurring in 1.17.17. I have heard (from you via Jacob) that `cargo update` will resolve this but running 

```
cargo update
anchor init anchor-test --template=multiple
cd anchor-test
anchor build
```

Still produces this error.

**Comment by acheroncrypto** [comment] 2024-01-26 22:12
Yes, the version I was talking about was from the logs you've shared:

> ```
> % anchor build
>    Compiling solana-frozen-abi v1.17.14
> ```

it's not your `solana-cli` version.

> I have heard (from you via Jacob) that `cargo update` will resolve this but running
> 
> ```
> cargo update
> anchor init anchor-test --template=multiple
> cd anchor-test
> anchor build
> ```
> 
> Still produces this error.

`cargo update` command needs to be run in a `cargo` workspace, not before the workspace is crated. It updates the dependencies to the latest SemVer compatible versions.

You can see which version of Solana crates you have by running:

```
cargo tree -i solana-program
```

You can also **only** update Solana deps with:

```
cargo update -p solana-program --precise 1.17.17
```

**Comment by mikemaccana** [comment] 2024-01-29 19:23
Cool. I can't do this right now (I have a deadline and my Anchor program breaks when I run `cargo update -p solana-program --precise 1.17.17`) but I can check this out at some point in the future when I have time. 

```
% cargo update -p solana-program --precise 1.17.17
    Updating crates.io index
error: failed to select a version for `ahash`.
    ... required by package `solana-frozen-abi v1.17.17`
    ... which satisfies dependency `solana-frozen-abi = "=1.17.17"` of package `solana-program v1.17.17`
    ... which satisfies dependency `solana-program = "^1.16"` of package `anchor-lang v0.29.0`
    ... which satisfies dependency `anchor-lang = "^0.29.0"` (locked to 0.29.0) of package `anchor-spl v0.29.0`
    ... which satisfies dependency `anchor-spl = "^0.29.0"` (locked to 0.29.0) of package `revealer v0.1.0 (/Users/mikemaccana/Code/solana/anchor-test/programs/anchor-test)`
versions that meet the requirements `=0.8.5` are: 0.8.5

all possible versions conflict with previously selected packages.

  previously selected package `ahash v0.8.4`
    ... which satisfies dependency `ahash = "=0.8.4"` of package `revealer v0.1.0 (/Users/mikemaccana/Code/solana/anchor-test/programs/anchor-test)`

failed to select a version for `ahash` which could resolve this conflict
```

My main priority is other people's machines though, so I've made [another repo with a workflow to check Anchor is working out of the box](https://github.com/mikemaccana/anchor-out-of-the-box). Right now though that can't finish the install process but have filed a separate issue for that.

**Comment by acheroncrypto** [comment] 2024-02-04 07:52
`solana-cli 1.18.0` which has a newer version of `rustc` got released so this particular error is not a problem anymore.

**Closed by acheroncrypto** 2024-02-04 07:52 UTC
Labels: duplicate, compile error
