### ISSUE TITLE
Instruction parameters are overwritten with random bytes, when instruction size is close to the limit and constraints are being used

### ISSUE THREAD

**Issue by serejkaaa512** [coral-xyz/anchor#3196] opened 2024-08-24 14:37 UTC
If instruction has some `#[account]` constraints with a lot of accounts being used and there is byte arrays or pubkeys in instruction parameters, then some random part inside them is overwritten with random bytes.

I've made an [example](https://github.com/serejkaaa512/anchor-error-example).

If you run `anchor test`, you can see, for example, the following:

- In test `address` in parameters is `Dcc6XavF27YRghRAbRz6nXdkPPCxFQn6QGARe3zNtDEL`
- In program log `address` is `11111111MTqikiemb67RkFxGXUHYRnutwFgf1dF9R`

If i remove `#[account]` constraint from one of the accounts inside the instruction, params are becoming equal.
If i use less accounts, params are becoming equal also.

Versions:
anchor-lang = "0.30.1"
solana-program = "1.18.22"

**Comment by acheroncrypto** [comment] 2024-08-25 08:26
Thanks for the report. This is a known issue and is being worked on. You're essentially going over the stack limit, but the compiler has a bug (as mentioned in https://github.com/coral-xyz/anchor/issues/3060), and it doesn't always tell you that you've gone over the stack, resulting in undefined behavior (same as https://github.com/coral-xyz/anchor/issues/3113#issuecomment-2248282731).

The compiler not telling you've gone over the stack should be fixed with solana v2, and we'll also have optimizations for our stack usage to fix this problem in the next version (see https://github.com/coral-xyz/anchor/pull/3194).

**Closed by acheroncrypto** 2024-08-25 08:26 UTC
Labels: bug, duplicate, lang

**Comment by acheroncrypto** [comment] 2024-09-02 15:43
> I'd suggest keeping this issue open and only marking it as complete once anchor supports solana v2 to make it clearer that this is a known issue which currently isn't solved yet.

This was closed because we have a bunch similar issues that are basically duplicate of https://github.com/coral-xyz/anchor/issues/2955 (don't mind the completed flag).

We're also upgrading to Solana v2 (https://github.com/coral-xyz/anchor/pull/3219), Solana v2 combined with https://github.com/coral-xyz/anchor/pull/2939 mostly solves this issue, which will be included in the next version.
