### ISSUE TITLE
initialized anchor project lifetime error

### ISSUE THREAD

**Issue by jim4067** [coral-xyz/anchor#2630] opened 2023-09-18 12:42 UTC
When initializing a new project, the `#[program]` attribute has a warning `struct takes 0 lifetime arguments but 1 lifetime argument was suppliedexpected 0 lifetime arguments`

This is easily solved by adding the `info` lifetime and an account to the `Accounts` struct.

**Comment by acheroncrypto** [comment] 2023-09-18 12:48
Does this happen when you build the program or only with Rust Analyzer?

Also supplying a lifetime argument to a struct that doesn't have a lifetime argument should be an error not a "warning".

**Comment by jim4067** [comment] 2023-09-18 12:51
Only happens with Rust analyzer. 

It is an error actually, but it's only appearing with Rust analyzer,

**Comment by acheroncrypto** [comment] 2023-09-18 13:26
The only warning I get on a new Anchor project(both with RA and the compiler) is the warning about the `ctx` variable not being used which is expected.

```
warning: unused variable: `ctx`
  --> programs/example/src/lib.rs:11:23
   |
11 |     pub fn initialize(ctx: Context<Initialize>) -> Result<()> {
   |                       ^^^ help: if this is intentional, prefix it with an underscore: `_ctx`
   |
   = note: `#[warn(unused_variables)]` on by default
   ```

If the compiler doesn't mention this error but the Rust Analyzer does, the most probable reason is that there is something wrong with your environment setup. A less probable reason would be a bug with Rust Analyzer itself but it's not very likely as I also use Rust Analyzer and don't have this problem.

I'd try resetting Rust Analyzer settings to default and see if it still reproduces.

> **Note**
When opening an issue like this, please also provide environment information such as the OS, Solana version, Anchor version, Rust Analyzer version so that there is a higher likelyhood of reproducability by the maintainers.

**Comment by jim4067** [comment] 2023-09-18 19:02
My environment Solana looks like this, 

anchor-cli v0.28.0
solana-cli v1.16.13 (src:b2a38f65; feat:3949673676, client:SolanaLabs)
solana-cargo-build-sbf v1.16.13
platform-tools v1.37
rustc v1.68.0
solana-clueter v1.16.11


I am using `Pop OS` and my Rust Analyzer version is `v0.4.1664` - pre-release

**Comment by acheroncrypto** [comment] 2023-11-09 08:56
Closing because this seems to be an issue with local setup/Rust Analyzer rather than Anchor as `anchor build` doesn't give an error but Rust Analyzer does.

**Closed by acheroncrypto** 2023-11-09 08:56 UTC
Labels: lang
