### ISSUE TITLE
Bug: Compile failed when install anchor 

### ISSUE THREAD

**Issue by ybina** [coral-xyz/anchor#3236] opened 2024-09-10 06:07 UTC
run:
```
apt-get update && sudo apt-get upgrade && sudo apt-get install -y pkg-config build-essential libudev-dev
cargo install --git https://github.com/coral-xyz/anchor --tag v0.30.1 anchor-cli --locked
```
report error:
```
error[E0282]: type annotations needed for `Box<_>`
  --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.29/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
   = note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update`
```

**Comment by developerfred** [comment] 2024-09-10 11:18
gm @ybina  try using old version to cargo 

`rustup override set 1.65.0`

**Comment by acheroncrypto** [comment] 2024-09-10 14:21
Duplicate of #3126, #3158, #3164, #3169, #3173, #3198, #3202.

**Closed by acheroncrypto** 2024-09-10 14:21 UTC
Labels: duplicate, avm, installation error
