### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'vec' in f32

### ISSUE THREAD

**Issue by alexajwhite** [coral-xyz/anchor#1744] opened 2022-04-07 05:22 UTC
I receive this error when trying to call the deployed program from a react front end. Seems to be an issue with the f32 and f64 data types, as using integers seem to work fine. Error comes from the idl file so it would most likely be on the program end.
<img width="538" alt="image" src="https://user-images.githubusercontent.com/6895599/162125722-ae56929d-1bdf-4ec9-8823-9d9678a29790.png">

**Comment by fanatid** [comment] 2022-04-11 09:52
Can you paste the code which causes an error?

**Comment by AdilSarwarNU** [comment] 2022-08-08 20:31
facing the same issue with f64

**Comment by acheroncrypto** [comment] 2023-12-05 22:59
Closing because there isn't enough information to reproduce. Feel free to reopen if you have a reproducable example.

**Closed by acheroncrypto** 2023-12-05 22:59 UTC
Labels: ts
