### ISSUE TITLE
Cannot build when having anchor-spl dependency

### ISSUE THREAD

**Issue by airicyu** [coral-xyz/anchor#3368] opened 2024-11-16 18:01 UTC
env:
- rustc 1.82.0
- solana 1.18.18
- anchor 0.30.1
OS: macOS

step 1: anchor init new project
step 2: add anchor-spl dependency

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"

step 3:
then cannot build with "anchor build"

build error:

```
   Compiling spl-token v4.0.3
   Compiling spl-type-length-value v0.4.6
   Compiling spl-token-group-interface v0.2.5
error[E0433]: failed to resolve: global paths cannot start with `crate`
 --> src/instruction.rs:4:5
  |
4 |     crate::{ check_program_account, error::TokenError },
  |     ^^^^^ global paths cannot start with `crate`

error[E0432]: unresolved import `TokenError::InvalidInstruction`
   --> src/instruction.rs:480:13
    |
480 |         use TokenError::InvalidInstruction;
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by acheroncrypto** [comment] 2024-11-19 13:35
I'm not able to reproduce the problem unfortunately. Your local crate cache might be corrupted, so I'd try clearing that. If that doesn't fix it, it's also possible for the Solana installation cache to get corrupted, so I'd try removing and reinstalling Solana toolchain.

Closing for now, but feel free to reopen if the problem continues after trying out the mentioned fixes.

**Closed by acheroncrypto** 2024-11-19 13:35 UTC
Labels: spl, compile error
