### ISSUE TITLE
Default "Hello World" - anchor build - anchor test - failing 

### ISSUE THREAD

**Issue by marsrobertson** [coral-xyz/anchor#3391] opened 2024-11-28 17:04 UTC
Following some tutorials / bootcamp.

`anchor init solana-encode-homework11-fresh`

All good:

```
yarn install v1.22.19
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning mocha > glob@7.2.0: Glob versions prior to v9 are no longer supported
warning mocha > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
✨  Done in 7.54s.
Failed to install node modules
Initialized empty Git repository in /Users/m/Code/solana-encode-homework11-fresh/.git/
solana-encode-homework11-fresh initialized
```

`cd solana-encode-homework11-fresh`
# `anchor build`

Appaears as good, just some warnings towards the end:

```
   Compiling proc-macro2 v1.0.92
   Compiling unicode-ident v1.0.14
   Compiling version_check v0.9.5
   Compiling typenum v1.17.0
   Compiling libc v0.2.166
   Compiling syn v1.0.109
   Compiling serde v1.0.215
   Compiling thiserror v1.0.69
   Compiling serde_json v1.0.133
   Compiling anyhow v1.0.93
   Compiling semver v1.0.23
   Compiling ryu v1.0.18
   Compiling itoa v1.0.14
   Compiling unicode-segmentation v1.12.0
   Compiling cfg-if v1.0.0
   Compiling memchr v2.7.4
   Compiling generic-array v0.14.7
   Compiling heck v0.3.3
   Compiling bs58 v0.5.1
   Compiling autocfg v1.4.0
   Compiling quote v1.0.37
   Compiling rustc_version v0.4.1
   Compiling syn v2.0.89
   Compiling cpufeatures v0.2.16
   Compiling jobserver v0.1.32
   Compiling shlex v1.3.0
   Compiling once_cell v1.20.2
   Compiling cc v1.2.1
   Compiling hashbrown v0.15.2
   Compiling equivalent v1.0.1
   Compiling subtle v2.6.1
   Compiling ahash v0.7.8
   Compiling ahash v0.8.11
   Compiling feature-probe v0.1.1
   Compiling toml_datetime v0.6.8
   Compiling indexmap v2.6.0
   Compiling winnow v0.6.20
   Compiling block-buffer v0.10.4
   Compiling crypto-common v0.1.6
   Compiling bv v0.11.1
   Compiling digest v0.10.7
   Compiling solana-frozen-abi-macro v1.18.26
   Compiling rustversion v1.0.18
   Compiling sha2 v0.10.8
   Compiling zerocopy v0.7.35
   Compiling cfg_aliases v0.2.1
   Compiling borsh v1.5.3
   Compiling memoffset v0.9.1
   Compiling solana-frozen-abi v1.18.26
   Compiling num-traits v0.2.19
   Compiling hashbrown v0.13.2
   Compiling toml_edit v0.22.22
   Compiling hashbrown v0.11.2
   Compiling arrayvec v0.7.6
   Compiling borsh-derive-internal v0.10.4
   Compiling borsh-derive-internal v0.9.3
   Compiling borsh-schema-derive-internal v0.9.3
   Compiling borsh-schema-derive-internal v0.10.4
   Compiling proc-macro-crate v3.2.0
   Compiling bs58 v0.4.0
   Compiling arrayref v0.3.9
   Compiling constant_time_eq v0.3.1
   Compiling lazy_static v1.5.0
   Compiling keccak v0.1.5
   Compiling log v0.4.22
   Compiling either v1.13.0
   Compiling itertools v0.10.5
   Compiling sha3 v0.10.8
   Compiling getrandom v0.2.15
   Compiling base64 v0.21.7
   Compiling blake3 v1.5.5
   Compiling solana-program v1.18.26
   Compiling anchor-derive-space v0.30.1
   Compiling serde_derive v1.0.215
   Compiling thiserror-impl v1.0.69
   Compiling bytemuck_derive v1.8.0
   Compiling borsh-derive v1.5.3
   Compiling solana-sdk-macro v1.18.26
   Compiling num-derive v0.4.2
   Compiling bytemuck v1.20.0
   Compiling serde_bytes v0.11.15
   Compiling bincode v1.3.3
   Compiling toml v0.5.11
   Compiling anchor-lang-idl-spec v0.1.0
   Compiling anchor-syn v0.30.1
   Compiling anchor-lang-idl v0.1.1
   Compiling proc-macro-crate v0.1.5
   Compiling borsh-derive v0.10.4
   Compiling borsh-derive v0.9.3
   Compiling borsh v0.10.4
   Compiling borsh v0.9.3
   Compiling anchor-attribute-constant v0.30.1
   Compiling anchor-derive-accounts v0.30.1
   Compiling anchor-attribute-event v0.30.1
   Compiling anchor-derive-serde v0.30.1
   Compiling anchor-attribute-access-control v0.30.1
   Compiling anchor-attribute-account v0.30.1
   Compiling anchor-attribute-error v0.30.1
   Compiling anchor-attribute-program v0.30.1
   Compiling anchor-lang v0.30.1
   Compiling solana-encode-homework11-fresh v0.1.0 (/Users/m/Code/solana-encode-homework11-fresh/programs/solana-encode-homework11-fresh)
    Finished release [optimized] target(s) in 50.35s
   Compiling proc-macro2 v1.0.92
   Compiling unicode-ident v1.0.14
   Compiling version_check v0.9.5
   Compiling typenum v1.17.0
   Compiling cfg-if v1.0.0
   Compiling serde v1.0.215
   Compiling libc v0.2.166
   Compiling syn v1.0.109
   Compiling autocfg v1.4.0
   Compiling subtle v2.6.1
   Compiling byteorder v1.5.0
   Compiling generic-array v0.14.7
   Compiling once_cell v1.20.2
   Compiling hashbrown v0.15.2
   Compiling anyhow v1.0.93
   Compiling equivalent v1.0.1
   Compiling memchr v2.7.4
   Compiling indexmap v2.6.0
   Compiling winnow v0.6.20
   Compiling serde_json v1.0.133
   Compiling thiserror v1.0.69
   Compiling quote v1.0.37
   Compiling syn v2.0.89
   Compiling itoa v1.0.14
   Compiling getrandom v0.2.15
   Compiling ryu v1.0.18
   Compiling rand_core v0.6.4
   Compiling block-buffer v0.10.4
   Compiling crypto-common v0.1.6
   Compiling num-traits v0.2.19
   Compiling semver v1.0.23
   Compiling cpufeatures v0.2.16
   Compiling digest v0.10.7
   Compiling unicode-segmentation v1.12.0
   Compiling crunchy v0.2.2
   Compiling either v1.13.0
   Compiling sha2 v0.10.8
   Compiling ahash v0.8.11
   Compiling heck v0.3.3
   Compiling getrandom v0.1.16
   Compiling bs58 v0.5.1
   Compiling crossbeam-utils v0.8.20
   Compiling paste v1.0.15
   Compiling rustc_version v0.4.1
   Compiling num-integer v0.1.46
   Compiling digest v0.9.0
   Compiling jobserver v0.1.32
   Compiling wasm-bindgen-shared v0.2.95
   Compiling num-bigint v0.4.6
   Compiling shlex v1.3.0
   Compiling rand_core v0.5.1
   Compiling libsecp256k1-core v0.2.2
   Compiling cc v1.2.1
   Compiling itertools v0.10.5
   Compiling crossbeam-epoch v0.9.18
   Compiling rayon-core v1.12.1
   Compiling crossbeam-deque v0.8.5
   Compiling ahash v0.7.8
   Compiling bumpalo v3.16.0
   Compiling log v0.4.22
   Compiling feature-probe v0.1.1
   Compiling wasm-bindgen-backend v0.2.95
   Compiling bv v0.11.1
   Compiling libsecp256k1-gen-genmult v0.2.1
   Compiling libsecp256k1-gen-ecmult v0.2.1
   Compiling borsh-derive-internal v0.10.4
   Compiling solana-frozen-abi-macro v1.18.26
   Compiling bitmaps v2.1.0
   Compiling im v15.1.0
   Compiling rustversion v1.0.18
   Compiling cfg_aliases v0.2.1
   Compiling tinyvec_macros v0.1.1
   Compiling opaque-debug v0.3.1
   Compiling borsh v1.5.3
   Compiling tinyvec v1.8.0
   Compiling blake3 v1.5.5
   Compiling rayon v1.10.0
   Compiling wasm-bindgen-macro-support v0.2.95
   Compiling sized-chunks v0.6.5
   Compiling libsecp256k1 v0.6.0
   Compiling borsh-schema-derive-internal v0.10.4
   Compiling borsh-derive-internal v0.9.3
   Compiling ark-serialize-derive v0.4.2
   Compiling derivative v2.2.0
   Compiling ark-ff-macros v0.4.2
   Compiling ark-ff-asm v0.4.2
   Compiling borsh-schema-derive-internal v0.9.3
   Compiling solana-frozen-abi v1.18.26
   Compiling rand_xoshiro v0.6.0
   Compiling aho-corasick v1.1.3
   Compiling memoffset v0.9.1
   Compiling wasm-bindgen v0.2.95
   Compiling serde_derive v1.0.215
   Compiling zerocopy-derive v0.7.35
   Compiling thiserror-impl v1.0.69
   Compiling zeroize_derive v1.4.2
   Compiling arrayref v0.3.9
   Compiling bs58 v0.4.0
   Compiling regex-syntax v0.8.5
   Compiling wasm-bindgen-macro v0.2.95
   Compiling zeroize v1.3.0
   Compiling bytemuck_derive v1.8.0
   Compiling zerocopy v0.7.35
   Compiling unicode-normalization v0.1.24
   Compiling hashbrown v0.11.2
   Compiling solana-program v1.18.26
   Compiling keccak v0.1.5
   Compiling ppv-lite86 v0.2.20
   Compiling memmap2 v0.5.10
   Compiling hashbrown v0.13.2
   Compiling rand_chacha v0.3.1
   Compiling rand_chacha v0.2.2
   Compiling arrayvec v0.7.6
   Compiling rand v0.8.5
   Compiling rand v0.7.3
   Compiling regex-automata v0.4.9
   Compiling lazy_static v1.5.0
   Compiling base64 v0.12.3
   Compiling rustc-hash v1.1.0
   Compiling constant_time_eq v0.3.1
   Compiling solana-sdk-macro v1.18.26
   Compiling bytemuck v1.20.0
   Compiling ark-std v0.4.0
   Compiling num-derive v0.4.2
   Compiling base64 v0.21.7
   Compiling anchor-derive-space v0.30.1
   Compiling regex v1.11.1
   Compiling serde_spanned v0.6.8
   Compiling toml_datetime v0.6.8
   Compiling toml v0.5.11
   Compiling anchor-lang-idl-spec v0.1.0
   Compiling serde_bytes v0.11.15
   Compiling toml_edit v0.22.22
   Compiling bitflags v2.6.0
   Compiling bincode v1.3.3
   Compiling crypto-mac v0.8.0
   Compiling proc-macro-crate v0.1.5
   Compiling hmac v0.8.1
   Compiling block-buffer v0.9.0
   Compiling hmac-drbg v0.3.0
   Compiling ark-serialize v0.4.2
   Compiling sha2 v0.9.9
   Compiling pbkdf2 v0.4.0
   Compiling tiny-bip39 v0.8.2
   Compiling borsh-derive v0.10.4
   Compiling borsh-derive v0.9.3
   Compiling sha3 v0.10.8
   Compiling curve25519-dalek v3.2.1
   Compiling ark-ff v0.4.2
   Compiling borsh v0.10.4
   Compiling borsh v0.9.3
   Compiling anchor-lang-idl v0.1.1
   Compiling toml v0.8.19
   Compiling proc-macro-crate v3.2.0
   Compiling cargo_toml v0.19.2
   Compiling borsh-derive v1.5.3
   Compiling anchor-syn v0.30.1
   Compiling anchor-attribute-error v0.30.1
   Compiling anchor-attribute-program v0.30.1
   Compiling anchor-attribute-constant v0.30.1
   Compiling anchor-derive-serde v0.30.1
   Compiling anchor-attribute-event v0.30.1
   Compiling anchor-attribute-account v0.30.1
   Compiling anchor-derive-accounts v0.30.1
   Compiling anchor-attribute-access-control v0.30.1
   Compiling ark-poly v0.4.2
   Compiling ark-ec v0.4.2
   Compiling ark-bn254 v0.4.0
   Compiling light-poseidon v0.2.0
   Compiling anchor-lang v0.30.1
   Compiling solana-encode-homework11-fresh v0.1.0 (/Users/m/Code/solana-encode-homework11-fresh/programs/solana-encode-homework11-fresh)
warning: unexpected `cfg` condition value: `custom-heap`
 --> programs/solana-encode-homework11-fresh/src/lib.rs:5:1
  |
5 | #[program]
  | ^^^^^^^^^^
  |
  = note: expected values for `feature` are: `cpi`, `default`, `idl-build`, `no-entrypoint`, `no-idl`, and `no-log-ix-name`
  = help: consider adding `custom-heap` as a feature in `Cargo.toml`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: `#[warn(unexpected_cfgs)]` on by default
  = note: this warning originates in the macro `$crate::custom_heap_default` which comes from the expansion of the attribute macro `program` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unexpected `cfg` condition value: `solana`
 --> programs/solana-encode-homework11-fresh/src/lib.rs:5:1
  |
5 | #[program]
  | ^^^^^^^^^^
  |
  = note: expected values for `target_os` are: `aix`, `android`, `cuda`, `dragonfly`, `emscripten`, `espidf`, `freebsd`, `fuchsia`, `haiku`, `hermit`, `horizon`, `hurd`, `illumos`, `ios`, `l4re`, `linux`, `macos`, `netbsd`, `none`, `nto`, `nuttx`, `openbsd`, `psp`, `psx`, `redox`, `rtems`, `solaris`, `solid_asp3`, `teeos`, `trusty`, `tvos`, `uefi`, `unknown`, `visionos`, and `vita` and 6 more
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: this warning originates in the macro `$crate::custom_heap_default` which comes from the expansion of the attribute macro `program` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unexpected `cfg` condition value: `custom-panic`
 --> programs/solana-encode-homework11-fresh/src/lib.rs:5:1
  |
5 | #[program]
  | ^^^^^^^^^^
  |
  = note: expected values for `feature` are: `cpi`, `default`, `idl-build`, `no-entrypoint`, `no-idl`, and `no-log-ix-name`
  = help: consider adding `custom-panic` as a feature in `Cargo.toml`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: this warning originates in the macro `$crate::custom_panic_default` which comes from the expansion of the attribute macro `program` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unexpected `cfg` condition value: `solana`
 --> programs/solana-encode-homework11-fresh/src/lib.rs:5:1
  |
5 | #[program]
  | ^^^^^^^^^^
  |
  = note: expected values for `target_os` are: `aix`, `android`, `cuda`, `dragonfly`, `emscripten`, `espidf`, `freebsd`, `fuchsia`, `haiku`, `hermit`, `horizon`, `hurd`, `illumos`, `ios`, `l4re`, `linux`, `macos`, `netbsd`, `none`, `nto`, `nuttx`, `openbsd`, `psp`, `psx`, `redox`, `rtems`, `solaris`, `solid_asp3`, `teeos`, `trusty`, `tvos`, `uefi`, `unknown`, `visionos`, and `vita` and 6 more
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: this warning originates in the macro `$crate::custom_panic_default` which comes from the expansion of the attribute macro `program` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unexpected `cfg` condition value: `anchor-debug`
 --> programs/solana-encode-homework11-fresh/src/lib.rs:5:1
  |
5 | #[program]
  | ^^^^^^^^^^
  |
  = note: expected values for `feature` are: `cpi`, `default`, `idl-build`, `no-entrypoint`, `no-idl`, and `no-log-ix-name`
  = help: consider adding `anchor-debug` as a feature in `Cargo.toml`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: this warning originates in the attribute macro `program` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unexpected `cfg` condition value: `anchor-debug`
 --> programs/solana-encode-homework11-fresh/src/lib.rs:5:1
  |
5 | #[program]
  | ^^^^^^^^^^
  |
  = note: expected values for `feature` are: `cpi`, `default`, `idl-build`, `no-entrypoint`, `no-idl`, and `no-log-ix-name`
  = help: consider adding `anchor-debug` as a feature in `Cargo.toml`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: this warning originates in the derive macro `Accounts` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: `solana-encode-homework11-fresh` (lib test) generated 11 warnings (5 duplicates)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 28.62s
     Running unittests src/lib.rs (/Users/m/Code/solana-encode-homework11-fresh/target/debug/deps/solana_encode_homework11_fresh-ac4d8c3a3d8d11c5)
```

# `anchor test`

```
Finished release [optimized] target(s) in 0.08s
warning: unexpected `cfg` condition value: `custom-heap`
 --> programs/solana-encode-homework11-fresh/src/lib.rs:5:1
  |
5 | #[program]
  | ^^^^^^^^^^
  |
  = note: expected values for `feature` are: `cpi`, `default`, `idl-build`, `no-entrypoint`, `no-idl`, and `no-log-ix-name`
  = help: consider adding `custom-heap` as a feature in `Cargo.toml`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: `#[warn(unexpected_cfgs)]` on by default
  = note: this warning originates in the macro `$crate::custom_heap_default` which comes from the expansion of the attribute macro `program` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unexpected `cfg` condition value: `solana`
 --> programs/solana-encode-homework11-fresh/src/lib.rs:5:1
  |
5 | #[program]
  | ^^^^^^^^^^
  |
  = note: expected values for `target_os` are: `aix`, `android`, `cuda`, `dragonfly`, `emscripten`, `espidf`, `freebsd`, `fuchsia`, `haiku`, `hermit`, `horizon`, `hurd`, `illumos`, `ios`, `l4re`, `linux`, `macos`, `netbsd`, `none`, `nto`, `nuttx`, `openbsd`, `psp`, `psx`, `redox`, `rtems`, `solaris`, `solid_asp3`, `teeos`, `trusty`, `tvos`, `uefi`, `unknown`, `visionos`, and `vita` and 6 more
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: this warning originates in the macro `$crate::custom_heap_default` which comes from the expansion of the attribute macro `program` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unexpected `cfg` condition value: `custom-panic`
 --> programs/solana-encode-homework11-fresh/src/lib.rs:5:1
  |
5 | #[program]
  | ^^^^^^^^^^
  |
  = note: expected values for `feature` are: `cpi`, `default`, `idl-build`, `no-entrypoint`, `no-idl`, and `no-log-ix-name`
  = help: consider adding `custom-panic` as a feature in `Cargo.toml`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: this warning originates in the macro `$crate::custom_panic_default` which comes from the expansion of the attribute macro `program` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unexpected `cfg` condition value: `solana`
 --> programs/solana-encode-homework11-fresh/src/lib.rs:5:1
  |
5 | #[program]
  | ^^^^^^^^^^
  |
  = note: expected values for `target_os` are: `aix`, `android`, `cuda`, `dragonfly`, `emscripten`, `espidf`, `freebsd`, `fuchsia`, `haiku`, `hermit`, `horizon`, `hurd`, `illumos`, `ios`, `l4re`, `linux`, `macos`, `netbsd`, `none`, `nto`, `nuttx`, `openbsd`, `psp`, `psx`, `redox`, `rtems`, `solaris`, `solid_asp3`, `teeos`, `trusty`, `tvos`, `uefi`, `unknown`, `visionos`, and `vita` and 6 more
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: this warning originates in the macro `$crate::custom_panic_default` which comes from the expansion of the attribute macro `program` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unexpected `cfg` condition value: `anchor-debug`
 --> programs/solana-encode-homework11-fresh/src/lib.rs:5:1
  |
5 | #[program]
  | ^^^^^^^^^^
  |
  = note: expected values for `feature` are: `cpi`, `default`, `idl-build`, `no-entrypoint`, `no-idl`, and `no-log-ix-name`
  = help: consider adding `anchor-debug` as a feature in `Cargo.toml`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: this warning originates in the attribute macro `program` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unexpected `cfg` condition value: `anchor-debug`
 --> programs/solana-encode-homework11-fresh/src/lib.rs:5:1
  |
5 | #[program]
  | ^^^^^^^^^^
  |
  = note: expected values for `feature` are: `cpi`, `default`, `idl-build`, `no-entrypoint`, `no-idl`, and `no-log-ix-name`
  = help: consider adding `anchor-debug` as a feature in `Cargo.toml`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: this warning originates in the derive macro `Accounts` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: `solana-encode-homework11-fresh` (lib test) generated 11 warnings (5 duplicates)
    Finished `test` profile [unoptimized + debuginfo] target(s) in 0.09s
     Running unittests src/lib.rs (/Users/m/Code/solana-encode-homework11-fresh/target/debug/deps/solana_encode_homework11_fresh-ac4d8c3a3d8d11c5)

Found a 'test' script in the Anchor.toml. Running it as a test suite!

Running test suite: "/Users/m/Code/solana-encode-homework11-fresh/Anchor.toml"

yarn run v1.22.19
$ /Users/m/Code/solana-encode-homework11-fresh/node_modules/.bin/ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'

Error: target/idl/solana_encode_homework_11_fresh.json doesn't exist. Did you run `anchor build`?
    at Object.get (/Users/m/Code/solana-encode-homework11-fresh/node_modules/@coral-xyz/anchor/src/workspace.ts:65:15)
    at Suite.<anonymous> (/Users/m/Code/solana-encode-homework11-fresh/tests/solana-encode-homework11-fresh.ts:9:36)
    at Object.create (/Users/m/Code/solana-encode-homework11-fresh/node_modules/mocha/lib/interfaces/common.js:148:19)
    at context.describe.context.context (/Users/m/Code/solana-encode-homework11-fresh/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Object.<anonymous> (/Users/m/Code/solana-encode-homework11-fresh/tests/solana-encode-homework11-fresh.ts:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module.m._compile (/Users/m/Code/solana-encode-homework11-fresh/node_modules/ts-node/src/index.ts:439:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/m/Code/solana-encode-homework11-fresh/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.exports.requireOrImport (/Users/m/Code/solana-encode-homework11-fresh/node_modules/mocha/lib/nodejs/esm-utils.js:60:20)
    at Object.exports.loadFilesAsync (/Users/m/Code/solana-encode-homework11-fresh/node_modules/mocha/lib/nodejs/esm-utils.js:103:20)
    at singleRun (/Users/m/Code/solana-encode-homework11-fresh/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at Object.exports.handler (/Users/m/Code/solana-encode-homework11-fresh/node_modules/mocha/lib/cli/run.js:374:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by acheroncrypto** [comment] 2024-11-29 17:20
```
Error: target/idl/solana_encode_homework_11_fresh.json doesn't exist. Did you run `anchor build`?
```

The error message is not great — we should definitely improve it. The reason for the error is the case conversion of numbers, which was explained in https://github.com/coral-xyz/anchor/issues/3353#issuecomment-2465892617.

Essentially, you named your program `solana-encode-homework11-fresh`, and during the case conversion from camelCase, it assumes as if there was a `-` before the `11`. Here are some ways you can fix this:

- Rename the program to have `-` before `11`, e.g. `solana-encode-homework-11-fresh`
- Rename the IDL file in `target/idl` to be `solana_encode_homework_11_fresh.json`
- Avoid having numbers in program names

Related: The warnings related to "unexpected `cfg` condition value" has been fixed in https://github.com/coral-xyz/anchor/pull/3396.

We should prioritize fixing this, especially given it's been reported multiple times now.

Thanks for creating the issue, but I'm closing this as duplicate of https://github.com/coral-xyz/anchor/issues/3353 to not divert attention.

**Closed by acheroncrypto** 2024-11-29 17:20 UTC
Labels: bug, duplicate, ts
