### ISSUE TITLE
[ERROR cargo_build_sbf] Failed to obtain package metadata: `cargo metadata` exited with an error: warning: `C:\Users\Administrator\.cargo\config` is deprecated in favor of `config.toml`     note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`

### ISSUE THREAD

**Issue by dlnuchunge** [coral-xyz/anchor#2990] opened 2024-05-28 09:01 UTC
[ERROR cargo_build_sbf] Failed to obtain package metadata: `cargo metadata` exited with an error: warning: `C:\Users\Administrator\.cargo\config` is deprecated in favor of `config.toml`   

error: failed to load manifest for workspace member `\\?\E:\web3\anchorsolana\programs\*`
    referenced by workspace at `\\?\E:\web3\anchorsolana\Cargo.toml`

![image](https://github.com/coral-xyz/anchor/assets/25683599/ad523fe3-6834-4e33-b6d1-1f0d92908923)

**Comment by acheroncrypto** [comment] 2024-05-28 09:17
Duplicate of https://github.com/coral-xyz/anchor/issues/2973, please see https://github.com/coral-xyz/anchor/issues/2973#issuecomment-2118656544.

**Closed by acheroncrypto** 2024-05-28 09:17 UTC
Labels: installation error
