### ISSUE TITLE
anchor idl fetch randomly stops working - no such file or directory (os error 2)

### ISSUE THREAD

**Issue by shrimpyuk** [coral-xyz/anchor#2740] opened 2023-12-20 17:40 UTC
anchor idl fetch has entirely stopped working and just says no such file or directory found, i'm unsure what its looking for and have no way to fix this. this is on arm64 mac, my macbook has same solana and anchor version installed and works fine.
![CleanShot 2023-12-20 at 17 39 30@2x](https://github.com/coral-xyz/anchor/assets/55786013/4d3190f7-bdc5-4196-a7b8-332f7fd797fd)

**Comment by acheroncrypto** [comment] 2023-12-20 18:23
Do other commands work?

**Comment by shrimpyuk** [comment] 2023-12-20 23:11
> Do other commands work?

seemingly so e.g. can create a new project etc, but this is the only functionality i need - grabbing idl's

**Comment by acheroncrypto** [comment] 2023-12-21 11:19
Unfortunately I'm not able to reproduce this, will need more info e.g. does `anchor init example && cd example && anchor keys list` work? Asking because it doesn't seem like there is any code that would fail only with `idl fetch` but not others.

**Comment by shrimpyuk** [comment] 2023-12-21 16:19
> Unfortunately I'm not able to reproduce this, will need more info e.g. does `anchor init example && cd example && anchor keys list` work? Asking because it doesn't seem like there is any code that would fail only with `idl fetch` but not others.

i don't know how but doing this seemed to of fixed it, maybe some yarn dependancies were missing

**Comment by acheroncrypto** [comment] 2023-12-22 09:58
Interesting, closing then.

**Closed by acheroncrypto** 2023-12-22 09:58 UTC
Labels: cli
