### ISSUE TITLE
[workspace.members] not supporting wildcards in Anchor.toml

### ISSUE THREAD

**Issue by GabrielePicco** [coral-xyz/anchor#2784] opened 2024-01-23 15:59 UTC
In a Anchor workspace, using workspace.members in the Anchor.toml does not work.

Adding the following to Anchor.toml:

```yaml
[workspace]
members = [
    "programs/*",
]
```

results in:

```bash
thread 'main' panicked at cli/src/config.rs:314:25:
Error reading workspace.members. File "programs/*" does not exist at path "/test-new/Anchor.toml"
```

Specifying a single member without wildcard instead works:
```yaml
[workspace]
members = [
    "programs/test-new/",
]
```

To my understanding from the [doc](https://www.anchor-lang.com/docs/manifest), `programs/*` should be equivalent to the default behaviour.

This issue prevent to organize several anchor programs in subfolders.

The root cause seems to be the [canonicalize_workspace](https://github.com/coral-xyz/anchor/blob/ef3b1493484e9d193f3cb270753484c30f75bcd8/cli/src/config.rs#L307) which should probably use a flat_map and expand the wildcard. Happy to draft a PR if this is a potential solution.

**Comment by acheroncrypto** [comment] 2024-01-23 17:04
> The root cause seems to be the [canonicalize_workspace](https://github.com/coral-xyz/anchor/blob/ef3b1493484e9d193f3cb270753484c30f75bcd8/cli/src/config.rs#L307) which should probably use a flat_map and expand the wildcard. Happy to draft a PR if this is a potential solution.

Yes, we can manually handle the `/*` case which is the most common case as you suggested. We could also add glob support so that we don't have to manually handle it but I'm fine with both solutions.

Feel free to send a PR for this but I'm closing this issue as it's duplicate of https://github.com/coral-xyz/anchor/issues/2658.

**Closed by acheroncrypto** 2024-01-23 17:04 UTC
Labels: duplicate, cli

**Comment by GabrielePicco** [comment] 2024-01-23 18:19
I missed the issue that was already opened. I've opened a PR addressing the simpler case: https://github.com/coral-xyz/anchor/pull/2785.
